### ISSUE TITLE
Hi, I made a fork :)

### ISSUE THREAD

**Issue by fa7ad** [itsniaz/AIUB-Notes-Crawler#3]
Hey,
I hope you don't mind. I made a copy of your project (I didn't know it was on github), made a few changes and published it on PyPI. Here's the [project](/fa7ad/aiub-notes-dl)

**Comment by itsniaz** [comment]
Thanks for your contribution. Good work publishing on PyPI with credit 👍 I link to your repo and PyPI and my description.
